[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci",
  "cd backend && npm ci"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate && npx tsc",
  "npx vite build"
]

[start]
cmd = "node backend/dist/index.js"
