export { HomePage } from "./HomePage";
export { default as PricingPage } from "./PricingPage";
export { AboutPage } from "./AboutPage";
export { ContactPage } from "./ContactPage";
export { default as AuthPage } from "./AuthPage";
export { default as DashboardPage } from "./DashboardPage";
export { default as InspectionsPage } from "./InspectionsPage";
export { default as ApplicationsPage } from "./ApplicationsPage";
export { default as AdminPage } from "./AdminPage";
export { PropertiesPage } from "./PropertiesPage";
export { PaymentCollectionPage } from "./PaymentCollectionPage";
export { LeaseManagementPage } from "./LeaseManagementPage";
export { TenantPortalPage } from "./TenantPortalPage";
export { LandlordPortalPage } from "./LandlordPortalPage";
export { DeveloperPortalPage } from "./DeveloperPortalPage";
export { MaintenanceRequestPage } from "./MaintenanceRequestPage";
export { default as PredictiveMaintenancePage } from "./maintenance/predictive";
export { ReportingDashboardPage } from "./ReportingDashboardPage";
export { default as OnboardingPage } from "../modules/onboarding/pages/OnboardingPage";
export { CommunicationPage } from "../modules/communication/pages/CommunicationPage";
export { AccountingDashboard as AccountingDashboardPage } from "../modules/accounting/pages/AccountingDashboard";
